---
host_power:
  name: ESXi Host Power
  description: Sends power commands to vCenter/ESXi Host
  fields:
    host:
      description: Host/vCenter target
      example: 192.168.1.1
    target_host:
      description: |
        (Optional) Specific ESXi host name to target when using vCenter with multiple hosts.
        If not specified and only one host is available, that host will be used.
        Required when vCenter manages multiple hosts.
      example: 'esxi01.example.com'
    command:
      description: Power command to run against ESXi host
      example: 'reboot|shutdown'
    force:
      description: |
        Flag to specify whether or not the host should be shut down/rebooted regardless
        of whether it is in maintenance mode. If true, the host is shut down/rebooted,
        even if there are virtual machines running or other operations in progress.
      example: 'true|false'

list_hosts:
  name: List ESXi Hosts
  description: Lists all ESXi hosts available in vCenter (useful for discovering target_host names)
  fields:
    host:
      description: Host/vCenter target
      example: 192.168.1.1

list_power_policies:
  name: List Power Policies
  description: Lists all available power policies for a specific ESXi host
  fields:
    host:
      description: Host/vCenter target to connect to
      example: 192.168.1.1
    target_host:
      description: >
        (Optional for single ESXi, Required for vCenter) Specific ESXi host name to check policies for.
        Use the 'list_hosts' service to discover available host names in vCenter.
      example: 'esxi01.domain.com'

host_power_policy:
  name: Host Power Policy
  description: Changes ESXi Host Power Policy (supports both ESXi and vCenter)
  fields:
    host:
      description: Host/vCenter target to connect to
      example: 192.168.1.1
    command:
      description: Type of power policy to apply
      example: 'static|dynamic|low'
    target_host:
      description: >
        (Optional for single ESXi, Required for vCenter) Specific ESXi host name to configure.
        Use the 'list_hosts' service to discover available host names in vCenter.
      example: 'esxi01.domain.com'

vm_power:
  name: Virtual Machine Power
  description: Sends Virtual Machine power commands to vCenter/ESXi Host
  fields:
    host:
      description: Host/vCenter where a Virtual Machine resides
      example: 192.168.1.1
    vm:
      description: Name of the Virtual Machine
      example: 'vm_name'
    command:
      description: Power command to run against Virtual Machine
      example: 'on|off|reboot|reset|shutdown|suspend'

create_snapshot:
  name: Create Virtual Machine Snapshot
  description: |
    Sends a command to vCenter/ESXi Host to take a Virtual Machine snapshot. For
    detailed information about snapshots see https://kb.vmware.com/s/article/1015180
  fields:
    host:
      description: Host/vCenter where a Virtual Machine resides
      example: 192.168.1.1
    vm:
      description: Name of the Virtual Machine
      example: 'vm_name'
    name:
      description: Name of the snapshot
      example: 'before hass update'
    description:
      description: (OPTIONAL) A description for this snapshot
      example: 'snapshot before big breaking change'
    memory:
      description: (OPTIONAL) Take snapshot with memory dump
      example: 'true|false (default: false)'
    quiesce:
      description: |
        (OPTIONAL) Quiesce VM's file system.
        Only used if VM is running and VM Tools are installed.
      example: 'true|false (default: false)'

remove_snapshot:
  name: Remove Virtual Machine Snapshot
  description: |
    Sends a command to vCenter/ESXi Host to remove a Virtual Machine snapshot
  fields:
    host:
      description: Host/vCenter where a Virtual Machine resides
      example: 192.168.1.1
    vm:
      description: Name of the Virtual Machine
      example: 'vm_name'
    command:
      description: Which snapshot to remove
      example: 'all|first|last'
