---
#######################################################################################
# This is a simplified version of ui-lovelace.yaml that can be used as a template     #
# for creating custom flex-horseshoe-cards. For more detailed configuration           #
# information see github pages of for these cards                                     #
#                                                                                     #
# You will need to get 'decluttering_card_templates.yaml' file, location in the same  #
# location as this file                                                               #
# User input is identified by '## CHANGE NEEDED' comments                            #
#                                                                                     #
# NOTE: ESXi Stats creates individual sensors for each attribute                  #
#######################################################################################

######## Add your resources. This example is based on HACS locations
resources:
  ## https://github.com/AmoebeLabs/flex-horseshoe-card
  - url: /community_plugin/flex-horseshoe-card/flex-horseshoe-card.js
    type: module

  ## https://github.com/custom-cards/decluttering-card
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module

#######################################################################################
# Register decluttering card template that is included in a seperate YAML             #
#                                                                                     #
# For this example we're going to assume that the template yaml is located in the     #
# same place as ui-lovelace.yaml. You will need to modify the path to match your      #
# installaion                                                                         #
#######################################################################################
decluttering_templates: !include decluttering_card_templates.yaml

######## Create a view
views:
  ## CHANGE NEEDED BELOW
  title: <TITLE>
  cards:
    - type: custom:decluttering-card
      template: vm_flex_template
      variables:
        ## CHANGE NEEDED BELOW
        ## Replace with your actual VM sensor entity names
        ## Individual sensors are now created for each attribute
        ## Examples: sensor.<vm_name>_cpu_use_pct, sensor.<vm_name>_memory_used_pct
        - entity: sensor.<vm_name>_cpu_use_pct  # Replace with actual VM CPU sensor
        ## In the example picture this is
        ## seen as 'DKR02' at the bottom
        ## of the card
        - name: <VM_NAME>
