---
## Install flex-table-card from here https://github.com/custom-cards/flex-table-card
## ESXi Stats creates individual sensors for each attribute
## Update entity patterns to match your actual sensor names
resources:
  - url: /local/flex-table-card/flex-table-card.js
    type: js

views:
  - title: ESXi Stats Example
    panel: true
    cards:
      - type: vertical-stack
        cards:
          # UI Controls Section
          - type: horizontal-stack
            cards:
              - type: entities
                title: VM Controls
                entities:
                  # VM Power Switches - Replace pattern with your actual switches
                  - switch.*_vm_switch_*
                  # VM Snapshot Buttons - Replace pattern with your actual buttons
                  - button.*_vm_snapshot_*
              - type: entities
                title: Host Controls
                entities:
                  # Host Power Switches - Replace pattern with your actual switches
                  - switch.*_host_switch_*
                  # Host Reboot Buttons - Replace pattern with your actual buttons
                  - button.*_host_reboot_*
                  # Power Policy Selectors - Replace pattern with your actual selectors
                  - select.*_power_policy

          # Individual Host Sensors
          - type: custom:flex-table-card
            title: ESXi Hosts
            clickable: true
            entities:
              # Include individual host sensors - replace with your actual sensor names
              include: sensor.*_name  # Host name sensors
            columns:
              - name: Name
                data: state
              - name: Version
                data: state
                entity_id: sensor.*_version
              - name: Uptime (H)
                data: state
                entity_id: sensor.*_uptime_hours
              - name: CPU Use (GHz)
                data: state
                entity_id: sensor.*_cpuusage_ghz
              - name: Mem Use (GB)
                data: state
                entity_id: sensor.*_memusage_gb
          # Individual VM Sensors
          - type: custom:flex-table-card
            title: ESXi Virtual Machines
            clickable: true
            entities:
              # Include individual VM sensors - replace with your actual sensor names
              include: sensor.*_name  # VM name sensors
            columns:
              - name: Name
                data: state
              - name: Status
                data: state
                entity_id: sensor.*_status
              - name: State
                data: state
                entity_id: sensor.*_state
              - name: Uptime (H)
                data: state
                entity_id: sensor.*_uptime_hours
              - name: CPU Usage (%)
                data: state
                entity_id: sensor.*_cpu_use_pct
              - name: CPUs
                data: state
                entity_id: sensor.*_cpu_count
              - name: Mem Use (MB)
                data: state
                entity_id: sensor.*_memory_used_mb
              - name: Mem Total (MB)
                data: state
                entity_id: sensor.*_memory_allocated_mb
              - name: Storage Used (GB)
                data: state
                entity_id: sensor.*_used_space_gb
              - name: VM Tools
                data: state
                entity_id: sensor.*_tools_status
              - name: Snapshots
                data: state
                entity_id: sensor.*_snapshots
          # Datastore Sensors (still use legacy format)
          - type: custom:flex-table-card
            title: ESXi Datastores
            clickable: true
            entities:
              include: sensor.esxi_datastore_*
            columns:
              - name: Name
                data: name
              - name: Free Space (GB)
                data: free_space_gb
              - name: Capacity (GB)
                data: total_space_gb
              - name: Hosts
                data: connected_hosts
              - name: VMs
                data: virtual_machines
              - name: Type
                data: type
